version: "3.7"
services:
  boostore-service:
    build: .
    restart: always
    ports:
      - 7070:7070
    depends_on:
      - mongo-db
  mongo-db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017