spring:
  data:
    mongodb:
      host: localhost
      database: books
      port: 27017
promocodes:
  promos:
      cs:
        promocode: OFFER1
        discount: 10
        expireDate: 2021-08-26
      dt:
        promocode: OFFER1
        discount: 10
        expireDate: 2021-08-26
      kt:
        promocode: OFFER1
        discount: 10
        expireDate: 2021-08-26